# Global options:

[mypy]
python_version = 3.12
warn_unused_configs = True

[mypy-attributedict.*]
ignore_missing_imports = True

[mypy-faker.*]
ignore_missing_imports = True

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True